WebPres/urls.py
"""
WebPres project v1.
Generated by 'django-admin startproject' using Django 3.2.9.
By ronyman.com
"""


from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include, url
from apps.hello_world.admin import admin_site
from graphene_django.views import GraphQLView


urlpatterns = [
    # Core_urls
    path('admin/', admin.site.urls),
    path('myadmin/', admin.site.urls),# for user admin from profile
    path('graphql/', GraphQLView.as_view(graphiql=True)),
    path('', include('core.urls')),
    path('', include('blog.urls')),
    path('admin/', include('tinymce.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from . import views
from django.urls import path
from .views import blog, search, CategoryView, blogdetail
from .views import PostCreateView, PostUpdateView, PostDeleteView
urlpatterns = [
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    #New Setting
    path('post/', blog.as_view(), name="blog"),
    path('search', search, name="search"),
    path('category/<str:cats>/', CategoryView, name="category"),
    path('<slug:slug>/send-comment', views.send_comment, name="send_comment"),
    path('<slug:slug>/', blogdetail.as_view(), name="blog-detail"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date
from django.db.models.base import Model
from django.db.models.signals import pre_save
from blog.utils import unique_slug_generator
from tinymce.models import HTMLField

STATUS = (
    (0,"Draft"),
    (1,"Publish"),
)



class PostComment(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender.get_username()}'

class Categories(models.Model):
    categoryname = models.CharField(max_length=255)

    def __str__(self):
        return self.categoryname

class Post(models.Model):
    title = models.CharField(max_length=255)
    title_tag = models.CharField(max_length=255, default='Blog Post')
    slug = models.SlugField(max_length=255, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='images', null=True)
    body = HTMLField('Content')
    comments = models.ManyToManyField(PostComment, blank=True)
    post_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Categories, null=True, on_delete=models.PROTECT, related_name='category_set')

    def __str__(self):
        return self.title + ' | ' + str(self.author)

def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Post)

core/models.py
from django.db import models
from PIL import Image
from django.utils.timezone import now
from apps.user.models import User

class CoreUserProfile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

apps/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from apps.user.models import Profile
from apps.user import models



###edit profile form
class EditProfileForm(forms.Form):
    username = forms.CharField()
    about_me = forms.CharField(widget=forms.Textarea())
    image = forms.ImageField(required=False)

    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def clean_username(self):
        """
        This function throws an exception if the username has already been
        taken by another user
        """

        username = self.cleaned_data['username']
        if username != self.original_username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'A user with that username already exists.')
        return username

##################

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

# Create a UserUpdateForm to update username and email
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

##Add New
class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
    website_url = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 1}))
    facebook_url = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 1}))
    instagram_url = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 1}))
    twitter_url = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 1}))

    class Meta:
        model = Profile
        fields = ['bio', 'avatar', 'facebook_url', 'twitter_url','website_url', 'instagram_url' ]


class ProfilePageForm(forms.ModelForm):
    model = Profile
    fields = ['bio', 'avatar', 'facebook_url', 'twitter_url','website_url', 'instagram_url' ]
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
    website_url = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 1}))
    instagram_url = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 1}))
    twitter_url = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 1}))

blog/forms.py
from django import forms
#from .models import Comment
from django.http import HttpResponseRedirect
from django.shortcuts import render

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')


class PostForm(forms.ModelForm):
class Meta:
    model = Post
    fields = ('__all__',)

filebrowser/forms.py
# coding: utf-8

import os
import re

from django import forms
from django.utils.translation import gettext_lazy as _

from filebrowser.settings import FOLDER_REGEX
from filebrowser.utils import convert_filename


ALNUM_NAME_RE = re.compile(FOLDER_REGEX, re.U)

TRANSPOSE_CHOICES = (
    ("", u"-----"),
    ("0", _(u"Flip horizontal")),
    ("1", _(u"Flip vertical")),
    ("2", _(u"Rotate 90° CW")),
    ("4", _(u"Rotate 90° CCW")),
    ("3", _(u"Rotate 180°")),
)


class CreateDirForm(forms.Form):
    """
    Form for creating a folder.
    """

    name = forms.CharField(widget=forms.TextInput(attrs=dict({'class': 'vTextField'}, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)

    def __init__(self, path, *args, **kwargs):
        self.path = path
        self.site = kwargs.pop("filebrowser_site", None)
        super(CreateDirForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        "validate name"
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not ALNUM_NAME_RE.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # Folder must not already exist.
            if self.site.storage.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
        return convert_filename(self.cleaned_data['name'])


class ChangeForm(forms.Form):
    """
    Form for renaming a file/folder.
    """

    custom_action = forms.ChoiceField(label=_(u'Actions'), required=False)
    name = forms.CharField(widget=forms.TextInput(attrs=dict({'class': 'vTextField'}, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)

    def __init__(self, *args, **kwargs):
        self.path = kwargs.pop("path", None)
        self.fileobject = kwargs.pop("fileobject", None)
        self.site = kwargs.pop("filebrowser_site", None)
        super(ChangeForm, self).__init__(*args, **kwargs)

        # Initialize choices of custom action
        choices = [("", u"-----")]
        for name, action in self.site.applicable_actions(self.fileobject):
            choices.append((name, action.short_description))
        self.fields['custom_action'].choices = choices

    def clean_name(self):
        "validate name"
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not ALNUM_NAME_RE.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            #  folder/file must not already exist.
            if self.site.storage.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))) and os.path.join(self.path, convert_filename(self.cleaned_data['name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The Folder already exists.'))
            elif self.site.storage.isfile(os.path.join(self.path, convert_filename(self.cleaned_data['name']))) and os.path.join(self.path, convert_filename(self.cleaned_data['name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The File already exists.'))
        return convert_filename(self.cleaned_data['name'])

blog/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from .models import Post, Categories, PostComment
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseNotFound, Http404
###
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.
class blog(ListView):
   model = Post
   template_name = 'blog_list.html'
   context_object_name = 'posts'
   cats = Categories.objects.all()
   ordering = ['-post_date']
   paginate_by = 50

   def get_context_data(self, *args, **kwargs):
      cat_list = Categories.objects.all()
      latestpost_list = Post.objects.all().order_by('-post_date')[:50]
      context = super(blog, self).get_context_data(*args, **kwargs)
      context["cat_list"] = cat_list
      context["latestpost_list"] = latestpost_list
      return context

def search(request):
   template = 'search_list.html'
   query = request.GET.get('q')
   if query:
      posts = Post.objects.filter(Q(title__icontains=query) | Q(body__icontains=query)).order_by('-post_date')
   else:
      posts = Post.objects.all()

   cat_list = Categories.objects.all()
   latestpost_list = Post.objects.all().order_by('-post_date')[:50]
   paginator = Paginator(posts, 50)
   page = request.GET.get('page')
   posts = paginator.get_page(page)
   return render(request, template, {'posts':posts, 'cat_list': cat_list, 'latestpost_list':latestpost_list, 'query':query})

def CategoryView(request, cats):
   if Categories.objects.filter(categoryname=cats).exists():
      category_posts = Post.objects.filter(category__categoryname=cats).order_by('-post_date')
      cat_list = Categories.objects.all()
      latestpost_list = Post.objects.all().order_by('-post_date')[:10]
      paginator = Paginator(category_posts, 2)
      page = request.GET.get('page')
      category_posts = paginator.get_page(page)
      return render(request, 'category_list.html', {'cats':cats, 'category_posts':category_posts, 'cat_list': cat_list, 'latestpost_list':latestpost_list})
   else:
      raise Http404

class blogdetail(DetailView):
   model = Post
   template_name = 'blog_detail.html'

   def get_context_data(self, *args, **kwargs):
      cat_list = Categories.objects.all()
      latestpost_list = Post.objects.all().order_by('-post_date')[:15]
      context = super(blogdetail, self).get_context_data(*args, **kwargs)
      context["cat_list"] = cat_list
      context["latestpost_list"] = latestpost_list
      return context

@login_required(login_url='/login')
def send_comment(request, slug):
   message = request.POST.get('message')
   post_id = request.POST.get('post_id')
   post_comment = PostComment.objects.create(sender=request.user, message=message)
   post = Post.objects.filter(id=post_id).first()
   post.comments.add(post_comment)
   return redirect('.')


###########


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    #fields = ["title", "content", "image", "tags"]  # for Specifict Post
    fields = '__all__'

    def create(request):
        form = PostForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect('blog/posts_form.html')
    #return render(request,'blog/posts_form.html/',{'form':form})

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been created successfully.')
        return reverse_lazy("index")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.slug = slugify(form.cleaned_data['title'])
        obj.save()
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    #fields = ["title", "content", "image", "tags"]
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        update = True
        context['update'] = update

        return context

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been updated successfully.')
        return reverse_lazy("index")

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        messages.success(
            self.request, 'Your post has been deleted successfully.')
        return reverse_lazy("index")

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)
##################

templates/blog/add_post.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% load static %}
{% load bootstrap5 %}
{% block head-meta %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load crispy_forms_tags %}
  	<meta charset="utf-8">
  	<!--Add keywords that describe your project between the quotation marks. This helps search engines find and index your content-->
    <meta name="keywords" content="Post WebPres Blog , Opensource CMS Site builder.">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Webpres site</title>
    {% block title %}Hello World | WebPres.org{% endblock %}
</head>

<body>
{% block content %}
  <h3>WebPres Today's Post</h3>
{# Display a form #}
<form action="/add_post/" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
    {% bootstrap_javascript %}
  {% buttons %}
    <button type="submit" class="btn btn-dark">
      Submit
    </button>
  {% endbuttons %}
</form>
{% endblock %}


</block>
</body>

templates/blog/base.html
  <!DOCTYPE html>
{% load i18n %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/png" href="{% static 'Assets/brand/favicon.ico' %}"/>
    <!-- reference your installed Font Awesome Free package's files here -->
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
     <script src="{% static 'bootstrap_javascript_url' %}"></script>

    <!-- Our project just needs Font Awesome Free's Solid + Brand files -->
      <link href="{% static 'fontawesome_free/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
      <link href="{% static 'fontawesome_free/css/brands.css' %}" rel="stylesheet" type="text/css">
      <link href="{% static 'fontawesome_free/css/solid.css' %}" rel="stylesheet" type="text/css">
        <title>{% block bootstrap5_title %}|{{ title }}{% endblock %}</title>



    {# --- css --- #}
    {% block extra_css %}{% endblock %}

  </head>
{% block bootstrap5_content %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark"><!--main navbar-->
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="{% static 'Assets/brand/webpres-logo.png'%} " alt="" width="50" height="50" class="d-inline-block align-text-top">
  <span class="position-absolute badge rounded-pill bg-danger">
   V.1.0
  </span>

    </a>

      <li class="nav navbar-nav me-auto">

        <li class="nav-item">
        <a class="nav-link text-white" href="/">Home</a>
      </li>
          <li class="nav-item">
        <a class="nav-link text-white" href="https://docs.webpres.org/">Docs</a>
      </li>
          <li class="nav-item">
        <a class="nav-link text-white" href="http://forum.webpres.org/">Forums</a>
      </li>
      </li>
          <li class="nav-item">
        <a class="nav-link text-white" href="/post/">Blog</a>
      </li>


      </li>
          <li class="nav-item">
        <a class="nav-link text-white" href="https://github.com/WebPres-org/v1.0/"><i class="fab fa-github"></i>&nbsp;Fork</a>
      </li>

      </li>
          <li class="nav-item">
        <a class="nav-link text-white" href="https://buy.stripe.com/7sI3fY9TD5jE3KgdR0"><i class="fas fa-hand-holding-usd"></i>&nbsp;Donate</a>
      </li>


        <ul class="nav justify-content">
  <li class="nav-item">
        {% if user.is_authenticated %}
     <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href='#' id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Welcome {{request.user}}</a>
    <div class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
    <ul class="nav justify-content-start">
        <ul><a class="dropdown-item " href="{% url 'Myprofile' %}">My Profile</a></ul>
        <ul><a class="dropdown-item" href="{% url 'post_create' %}">Create Post</a></ul>
          <ul><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></ul>
    </ul>
      </li>
{% else %}
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'register' %}">Register</a>
      </li>
      <li class="nav-item">
        <li class="nav-item">
    <a class="nav-link text-white btn btn-outline-danger " href="{% url 'login' %}">Login</a>
  </li>
      </li>
      {% endif %}

  </li>
 </li>
    </ul>
      </div>
    </div>
    </nav>
 {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

{% endblock %}

<!--start Body-->
<body>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<main class="container">

  <!-- templates/base.html -->

<!-- ... -->

{% if request.user.is_authenticated %}
<div class="navbar-nav ml-auto">
  <a href="{% url 'core:post_create' %}"
    class="nav-item nav-link {% if request.path == '/post/create/' %}active{% endif %}">
    Create a post
  </a>
  <!-- ... -->
{% endif %}

<!-- ... -->
      {% block content %}{% endblock %}

</main>
    {# --- js --- #}
    {% block extra_js %}{% endblock %}

</body>
</html>

templates/blog/post.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% load static %}
{% load bootstrap5 %}
{% block head-meta %}
  	<meta charset="utf-8">
  	<!--Add keywords that describe your project between the quotation marks. This helps search engines find and index your content-->
    <meta name="keywords" content="WebPres.org , Blog Post.">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Webpres site</title>
    {% block title %}Hello World | WebPres.org{% endblock %}
</head>

{% block head_title %}{{ post.title }}{% endblock %}
{% block content %}
<div class="container-fluid my-5">

<!-- ... -->

 <!-- List of comments -->
  {% if comments %}
  <div class="row mt-5">
    <div class="col-lg-6 offset-lg-3">
      Comment{{ comments.count|pluralize }}
      <span class="badge badge-dark ml-2">{{ comments.count }}</span>
    </div>

      {% for comment in comments %}
    <div class="col-lg-6 offset-lg-3 mt-2">
      <div class="card p-2">
        <div class="row">
          <div class="col-12">
            <img class="rounded-circle mr-2" src="{% static 'img/avatar.svg' %}" alt="Avatar">
            <strong>{{ comment.name }}</strong> said
          </div>
          <div class="col-12">
            <p class="m-1 mt-3">{{ comment.content }}</p>
            <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

    <!-- Form to leave comment -->
  <div class="row mt-5">
    <div class="col-lg-6 offset-lg-3">
      <h3>Leave a comment</h3>
      <form method='POST'>
        {% csrf_token %}
        <div class="form-group">
          <span class="ml-2"></span>{{ form.name.label_tag }}
          <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_name"
            name="name" value="{{ form.name.value|default:'' }}">
        </div>
        <div class="form-group">
          <span class="ml-2"></span>
          {{ form.email.label_tag }}
          <span class="text-muted"><small>(Your email address will not be published)</small></span>
          <input type="text" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
            name="email" value="{{ form.email.value|default:'' }}">
        </div>
        <div class="form-group">

            <span class="ml-2"></span>{{ form.content.label_tag }}
          <textarea class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
            name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
        </div>
        <button class="btn btn-primary ml-2" type="submit">Reply</button>
      </form>
    </div>
  </div>

</div>
{% endblock content %}

{% endblock  %}

templates/blog/post_confirm_delete.html
{% block head_title %}Delete post{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class=" my-5">Delete post</h2>
      <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete it?</p>
        <button type="submit" class="btn btn-danger">Submit
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/blog/post_form.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% load static %}
{% load bootstrap5 %}
{% load i18n %}
{% load static %}
{% load bootstrap5 %}
{% block head-meta %}
<!DOCTYPE html>
<html lang="en">
<head>
  	<meta charset="utf-8">
  	<!--Add keywords that describe your project between the quotation marks. This helps search engines find and index your content-->
    <meta name="keywords" content="WebPres.org , Post Forms.">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}

    <meta charset="UTF-8">
     {% block bootstrap5_title %} Create a Post | WebPres.org{% endblock %}
</head>
{% block head_title %}{% if update %}Update post{% else %}Create a post{% endif %}{% endblock head_title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h2 class=" my-5">{% if update %}Update post{% else %}Create a post{% endif %}</h2>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
          {{ form.title.label_tag }}
          <input type="text" class="form-control {% if form.title.errors %}is-invalid{% endif %}" id="id_title"
            name="title" value='{{ form.title.value|default:"" }}'>
          {% if form.title.errors %}
          <div class="invalid-feedback">{{ form.title.errors }}</div>
          {% endif %}
        </div>

<div class="form-group">
          {{ form.content.label_tag }}
          <textarea type="text" class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
            name="content" cols="40" rows="10">{{ form.content.value|default:"" }}</textarea>
          {% if form.content.errors %}
          <div class="invalid-feedback">{{ form.content.errors }}</div>
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.image.label_tag }}<br>
          <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image" name="image"
            accept="image/*">
          {% if form.image.errors %}
          <div class="invalid-feedback">{{ form.image.errors }}</div>
          {% endif %}
        </div>

          <div class="form-group">
          {{ form.tags.label_tag }}<br>
          <select class="custom-select w-25" name="tags" id="id_tags" multiple>
            {% for name, value in form.tags.field.choices %}
            <option value="{{ name }}">{{ value }}</option>
            {% endfor %}
          </select>
          {% if form.tags.errors %}
          <div class="invalid-feedback">{{ form.tags.errors }}</div>
          {% endif %}
        </div>
          </br>

        <button type="submit" class="btn btn-dark">
          {% if update %}Update the post{% else %}Create a post{% endif %}
        </button>
      </form>

        </div>
  </div>
</div>
{% include "legal/copyrights.html" %}
{% endblock content %}

templates/blog/posts_list.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>My Blog</title>
</head>
<body>
     <header>
       <h1> <a href="">My Personal Blog</a> </h1>
     </header>
     <div class="container">
       {% block content %}
         {% for i in object_list %}
             <div class="article">
             <h3><a href="">{{ i.title }}</a></h3>
               <p>{{ i.body }}</p>
            </div>
         {% endfor %}
        {% endblock content %}
     </div>
 </body>
</html>

templates/blog/sidebar.html
{% block sidebar %}
{% load static %}
{% load bootstrap5 %}
<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Me</h5>
    <div class="card-body">
        <p class="card-text">Lorem Ipsum sit dolor amet.</p>
        <a href="#"
           class="btn btn-danger">Contact me</a>
    </div>
</div>
</div>

{% endblock sidebar %}